### 3. 이미지 불러오기/저장하기

In [5]:
import numpy as np
import cv2

def showImage():
    imgfile = '../images/it_show.jpg'
    # 이미지 불러오기
    img = cv2.imread(imgfile, cv2.IMREAD_COLOR)
    img = cv2.resize(src=img, dsize=(1024, 768))
    # 창조절가능 이미지 뷰    
    cv2.namedWindow('it_show', cv2.WINDOW_NORMAL)
    cv2.imshow('it_show', img)
    # wait for keyboard input, unit(ms)
    # 파라미터 0인경우 무한 대기
    inputKey = cv2.waitKey(0)
    if inputKey == 27: # esc
        cv2.destroyAllWindows()
    elif inputKey == 26: # ctrl + z
        cv2.imwrite('../images/it_show_copy.jpg',img)
        cv2.destroyAllWindows()
    else:
        cv2.destroyAllWindows()
showImage()

In [7]:
import cv2

# 이미지 불러오기 및 크기 조절
sampleImg = cv2.imread("../images/it_show.jpg")
sampleImg = cv2.resize(src=sampleImg, dsize=(256,256))

# 불러온 이미지 내 사각형 그리기
rectImg = cv2.rectangle(sampleImg, (10,10), (200,200), (255,0,0))

cv2.imshow("img_show", rectImg)

k = cv2.waitKey(0)

if k==27:
    cv2.destroyAllWindows()
else:
    cv2.destroyAllWindows()


In [8]:
import cv2

# 이미지 불러오기 및 크기 조절
sampleImg = cv2.imread("../images/it_show.jpg")
sampleImg = cv2.resize(src=sampleImg, dsize=(256,256))

# 불러온 이미지 내 사각형 그리기
rectImg = cv2.rectangle(sampleImg, (10,10), (200,200), (255,0,0))
cv2.putText(rectImg,"haiteam",(0,100), cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0))

cv2.imshow("img_show", rectImg)

k = cv2.waitKey(0)

if k==27:
    cv2.destroyAllWindows()
else:
    cv2,destroyAllWindows()


In [9]:
import cv2
cap = cv2.VideoCapture("../images/hkcam.avi")
#cap = cv2.VideoCapture(0)

width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)

## 비디오가 정상적으로 열렸는지 확인
while (cap.isOpened):
    ret, frame = cap.read()
    
    if ret:
        cv2.imshow("video", frame)
        
        # 33ms 30fps = 1000ms/30frame -> 1000/30 = 33
        k = cv2.waitKey(33)
        if k == 27:
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [10]:
import datetime
import cv2

#capture = cv2.VideoCapture(0)
capture = cv2.VideoCapture("../images/image_sample.mp4")
fcc = cv2.VideoWriter_fourcc('D','I','V','X')
record = False

width = int(capture.get(3))
height = int(capture.get(4))

# 캡쳐 로직 (우측 참조)
while (capture.isOpened):
    ret, frame = capture.read()
    if ret == False:
        break
    cv2.imshow("VideoFrame", frame)

    now = datetime.datetime.now().strftime("%d_%H-%M-%S")
    key = cv2.waitKey(33)#1) & 0xFF

    if key == 27: # esc 종료
        break
    elif key == 26:   # ctrl + z
        print("캡쳐")
        cv2.imwrite("./" + str(now) + ".png", frame)

    elif key == 24:  # ctrl + x
        print("녹화 시작")
        record = True
        outfps = 30
        video = cv2.VideoWriter("./" + str(now) + ".avi", 
                                fcc, # 프레임 압축코드
                                outfps, 
                                (width, height))
    elif key == 3:
        print("녹화 중지") # ctrl + c
        record = False
        video.release()
    
    if record == True:
        print("녹화 중..")
        video.write(frame)

capture.release()
cv2.destroyAllWindows()


In [17]:
import datetime
import cv2

#capture = cv2.VideoCapture(0)
capture = cv2.VideoCapture("../images/image_sample.mp4")
fcc = cv2.VideoWriter_fourcc('D','I','V','X')
# fcc = cv2.VideoWriter_fourcc(*'XVID')
record = False

frame_width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))

while (capture.isOpened):
    ret, frame = capture.read()
    if ret == False:
        break
    cv2.imshow("VideoFrame", frame)

    now = datetime.datetime.now().strftime("%d_%H-%M-%S")
    key = cv2.waitKey(33)#1) & 0xFF
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    if key == 27: # esc 종료
        break
    elif key == 26:   # ctrl + z
        print("캡쳐")
#         gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        print(gray)
        cv2.imwrite("./" + str(now) + ".png", gray)

    elif key == 24:  # ctrl + x
        print("녹화 시작")
        record = True
        outfps = 30
#         video = cv2.VideoWriter(filename="./" + str(now) + ".avi", 
#                                 fourcc = fcc, # 프레임 압축코드
#                                 fps=outfps, 
#                                 frameSize= (frame_width, frame_height), isColor=False)
        video = cv2.VideoWriter("./" + str(now) + ".avi",
                       fcc,
                        20,
                        (frame_width,frame_height),
                        0
                       )
        
    elif key == 3:
        print("녹화 중지") # ctrl + c
        record = False
        video.release()
    
    if record == True:
        print("녹화 중.. 가로:"+str(frame_width)+"세로:"+str(frame_height))
        video.write(gray)

capture.release()
cv2.destroyAllWindows()


캡쳐
[[16 16 16 ...  5  5  5]
 [16 16 16 ...  5  5  5]
 [16 16 16 ...  5  5  5]
 ...
 [12 12 12 ... 15 15 15]
 [12 12 12 ... 15 15 15]
 [12 12 12 ... 15 15 15]]
녹화 시작
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중.. 가로:1920세로:1080
녹화 중지
